name: todos
description: Flutter Data Sample App!
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_data: ^0.4.2-dev.2
  json_annotation: ^3.0.1
  google_fonts: ^1.0.0
  path_provider: ^1.6.7
  flutter_data_state: ^0.3.1
  provider: ^4.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true